// Walks every asset the browser pulls when loading index.html and writes
// server/embedded-assets.ts. Each entry is `import path with { type: 'file' }`
// so `bun build --compile` bundles the bytes into the standalone executable.
// In dev (`bun run serve`) the same imports resolve to
// real filesystem paths, so the dev and prod paths run identical code.

import { mkdir, readdir, stat, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

const root = new URL('..', import.meta.url).pathname.replace(/\/$/, '')
const outFile = join(root, 'server/embedded-assets.ts')

const ROOTS = [
  { fsPath: join(root, 'index.html'), urlPath: '/index.html' },
]

async function walk(dir: string, out: string[]): Promise<void> {
  const entries = await readdir(dir, { withFileTypes: true })
  for (const e of entries) {
    if (e.name === '.DS_Store' || e.name.endsWith('.map')) continue
    const full = join(dir, e.name)
    if (e.isDirectory()) await walk(full, out)
    else out.push(full)
  }
}

const DIST_ASSET_DIRS = ['css', 'images', 'js', 'sound']
const distDir = join(root, 'dist')
const distExists = await stat(distDir).then(() => true, () => false)
const distFiles: string[] = []
if (distExists) {
  for (const dir of DIST_ASSET_DIRS) {
    const assetDir = join(distDir, dir)
    const exists = await stat(assetDir).then(s => s.isDirectory(), () => false)
    if (exists) await walk(assetDir, distFiles)
  }
}

const allFiles: { fsPath: string; urlPath: string }[] = [
  ...ROOTS,
  ...distFiles.map(f => ({
    fsPath: f,
    urlPath: '/' + relative(root, f).split('/').join('/'),
  })),
]

const lines: string[] = []
lines.push('// @ts-nocheck -- AUTO-GENERATED by scripts/generate-asset-manifest.ts')
lines.push('// Regenerated on `bun run build`. Do not edit by hand. Bun resolves')
lines.push('// `with { type: \'file\' }` to a string path at runtime; TS does not model')
lines.push('// that uniformly across asset types, hence the nocheck.')
lines.push('')

const importNames: string[] = []
allFiles.forEach((f, i) => {
  const name = `a${i}`
  importNames.push(name)
  const importPath = '../' + relative(root, f.fsPath)
  lines.push(`import ${name} from '${importPath}' with { type: 'file' }`)
})

lines.push('')
lines.push('export const embeddedAssets: Record<string, string> = {')
allFiles.forEach((f, i) => {
  lines.push(`  ${JSON.stringify(f.urlPath)}: ${importNames[i]},`)
  if (f.urlPath === '/index.html') {
    lines.push(`  "/": ${importNames[i]},`)
  }
})
lines.push('}')
lines.push('')

await mkdir(join(root, 'server'), { recursive: true })
await writeFile(outFile, lines.join('\n'))

console.log(`embedded-assets.ts: ${allFiles.length} files indexed`)
